[package]
name = "ptbri"
version = "0.1.0"
authors = ["arrudagates <arrudagates@gmail.com>"]
edition = "2018"


[dependencies]
lazy_static = "1.4.0"
once_cell = "1.7.2"
pest = "2.1.3"
pest_derive = "2.1.0"
quote = "1.0.9"
